# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/lib/python2.7/dist-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /usr/local/lib/python2.7/dist-packages/cmake/data/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/xmrig-cuda

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/xmrig-cuda/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/lib/python2.7/dist-packages/cmake/data/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/lib/python2.7/dist-packages/cmake/data/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/xmrig-cuda/build/CMakeFiles /root/xmrig-cuda/build/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/xmrig-cuda/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named xmrig-cuda

# Build rule for target.
xmrig-cuda: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xmrig-cuda
.PHONY : xmrig-cuda

# fast build rule for target.
xmrig-cuda/fast:
	$(MAKE) -f CMakeFiles/xmrig-cuda.dir/build.make CMakeFiles/xmrig-cuda.dir/build
.PHONY : xmrig-cuda/fast

#=============================================================================
# Target rules for targets named xmrig-cu

# Build rule for target.
xmrig-cu: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xmrig-cu
.PHONY : xmrig-cu

# fast build rule for target.
xmrig-cu/fast:
	$(MAKE) -f CMakeFiles/xmrig-cu.dir/build.make CMakeFiles/xmrig-cu.dir/build
.PHONY : xmrig-cu/fast

src/CudaCryptonightR_gen.o: src/CudaCryptonightR_gen.cpp.o

.PHONY : src/CudaCryptonightR_gen.o

# target to build an object file
src/CudaCryptonightR_gen.cpp.o:
	$(MAKE) -f CMakeFiles/xmrig-cuda.dir/build.make CMakeFiles/xmrig-cuda.dir/src/CudaCryptonightR_gen.cpp.o
.PHONY : src/CudaCryptonightR_gen.cpp.o

src/CudaCryptonightR_gen.i: src/CudaCryptonightR_gen.cpp.i

.PHONY : src/CudaCryptonightR_gen.i

# target to preprocess a source file
src/CudaCryptonightR_gen.cpp.i:
	$(MAKE) -f CMakeFiles/xmrig-cuda.dir/build.make CMakeFiles/xmrig-cuda.dir/src/CudaCryptonightR_gen.cpp.i
.PHONY : src/CudaCryptonightR_gen.cpp.i

src/CudaCryptonightR_gen.s: src/CudaCryptonightR_gen.cpp.s

.PHONY : src/CudaCryptonightR_gen.s

# target to generate assembly for a file
src/CudaCryptonightR_gen.cpp.s:
	$(MAKE) -f CMakeFiles/xmrig-cuda.dir/build.make CMakeFiles/xmrig-cuda.dir/src/CudaCryptonightR_gen.cpp.s
.PHONY : src/CudaCryptonightR_gen.cpp.s

src/KawPow/raven/CudaKawPow_gen.o: src/KawPow/raven/CudaKawPow_gen.cpp.o

.PHONY : src/KawPow/raven/CudaKawPow_gen.o

# target to build an object file
src/KawPow/raven/CudaKawPow_gen.cpp.o:
	$(MAKE) -f CMakeFiles/xmrig-cu.dir/build.make CMakeFiles/xmrig-cu.dir/src/KawPow/raven/CudaKawPow_gen.cpp.o
.PHONY : src/KawPow/raven/CudaKawPow_gen.cpp.o

src/KawPow/raven/CudaKawPow_gen.i: src/KawPow/raven/CudaKawPow_gen.cpp.i

.PHONY : src/KawPow/raven/CudaKawPow_gen.i

# target to preprocess a source file
src/KawPow/raven/CudaKawPow_gen.cpp.i:
	$(MAKE) -f CMakeFiles/xmrig-cu.dir/build.make CMakeFiles/xmrig-cu.dir/src/KawPow/raven/CudaKawPow_gen.cpp.i
.PHONY : src/KawPow/raven/CudaKawPow_gen.cpp.i

src/KawPow/raven/CudaKawPow_gen.s: src/KawPow/raven/CudaKawPow_gen.cpp.s

.PHONY : src/KawPow/raven/CudaKawPow_gen.s

# target to generate assembly for a file
src/KawPow/raven/CudaKawPow_gen.cpp.s:
	$(MAKE) -f CMakeFiles/xmrig-cu.dir/build.make CMakeFiles/xmrig-cu.dir/src/KawPow/raven/CudaKawPow_gen.cpp.s
.PHONY : src/KawPow/raven/CudaKawPow_gen.cpp.s

src/crypto/cn/c_blake256.o: src/crypto/cn/c_blake256.c.o

.PHONY : src/crypto/cn/c_blake256.o

# target to build an object file
src/crypto/cn/c_blake256.c.o:
	$(MAKE) -f CMakeFiles/xmrig-cuda.dir/build.make CMakeFiles/xmrig-cuda.dir/src/crypto/cn/c_blake256.c.o
.PHONY : src/crypto/cn/c_blake256.c.o

src/crypto/cn/c_blake256.i: src/crypto/cn/c_blake256.c.i

.PHONY : src/crypto/cn/c_blake256.i

# target to preprocess a source file
src/crypto/cn/c_blake256.c.i:
	$(MAKE) -f CMakeFiles/xmrig-cuda.dir/build.make CMakeFiles/xmrig-cuda.dir/src/crypto/cn/c_blake256.c.i
.PHONY : src/crypto/cn/c_blake256.c.i

src/crypto/cn/c_blake256.s: src/crypto/cn/c_blake256.c.s

.PHONY : src/crypto/cn/c_blake256.s

# target to generate assembly for a file
src/crypto/cn/c_blake256.c.s:
	$(MAKE) -f CMakeFiles/xmrig-cuda.dir/build.make CMakeFiles/xmrig-cuda.dir/src/crypto/cn/c_blake256.c.s
.PHONY : src/crypto/cn/c_blake256.c.s

src/crypto/common/Algorithm.o: src/crypto/common/Algorithm.cpp.o

.PHONY : src/crypto/common/Algorithm.o

# target to build an object file
src/crypto/common/Algorithm.cpp.o:
	$(MAKE) -f CMakeFiles/xmrig-cuda.dir/build.make CMakeFiles/xmrig-cuda.dir/src/crypto/common/Algorithm.cpp.o
.PHONY : src/crypto/common/Algorithm.cpp.o

src/crypto/common/Algorithm.i: src/crypto/common/Algorithm.cpp.i

.PHONY : src/crypto/common/Algorithm.i

# target to preprocess a source file
src/crypto/common/Algorithm.cpp.i:
	$(MAKE) -f CMakeFiles/xmrig-cuda.dir/build.make CMakeFiles/xmrig-cuda.dir/src/crypto/common/Algorithm.cpp.i
.PHONY : src/crypto/common/Algorithm.cpp.i

src/crypto/common/Algorithm.s: src/crypto/common/Algorithm.cpp.s

.PHONY : src/crypto/common/Algorithm.s

# target to generate assembly for a file
src/crypto/common/Algorithm.cpp.s:
	$(MAKE) -f CMakeFiles/xmrig-cuda.dir/build.make CMakeFiles/xmrig-cuda.dir/src/crypto/common/Algorithm.cpp.s
.PHONY : src/crypto/common/Algorithm.cpp.s

src/xmrig-cuda.o: src/xmrig-cuda.cpp.o

.PHONY : src/xmrig-cuda.o

# target to build an object file
src/xmrig-cuda.cpp.o:
	$(MAKE) -f CMakeFiles/xmrig-cuda.dir/build.make CMakeFiles/xmrig-cuda.dir/src/xmrig-cuda.cpp.o
.PHONY : src/xmrig-cuda.cpp.o

src/xmrig-cuda.i: src/xmrig-cuda.cpp.i

.PHONY : src/xmrig-cuda.i

# target to preprocess a source file
src/xmrig-cuda.cpp.i:
	$(MAKE) -f CMakeFiles/xmrig-cuda.dir/build.make CMakeFiles/xmrig-cuda.dir/src/xmrig-cuda.cpp.i
.PHONY : src/xmrig-cuda.cpp.i

src/xmrig-cuda.s: src/xmrig-cuda.cpp.s

.PHONY : src/xmrig-cuda.s

# target to generate assembly for a file
src/xmrig-cuda.cpp.s:
	$(MAKE) -f CMakeFiles/xmrig-cuda.dir/build.make CMakeFiles/xmrig-cuda.dir/src/xmrig-cuda.cpp.s
.PHONY : src/xmrig-cuda.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... xmrig-cuda"
	@echo "... xmrig-cu"
	@echo "... src/CudaCryptonightR_gen.o"
	@echo "... src/CudaCryptonightR_gen.i"
	@echo "... src/CudaCryptonightR_gen.s"
	@echo "... src/KawPow/raven/CudaKawPow_gen.o"
	@echo "... src/KawPow/raven/CudaKawPow_gen.i"
	@echo "... src/KawPow/raven/CudaKawPow_gen.s"
	@echo "... src/crypto/cn/c_blake256.o"
	@echo "... src/crypto/cn/c_blake256.i"
	@echo "... src/crypto/cn/c_blake256.s"
	@echo "... src/crypto/common/Algorithm.o"
	@echo "... src/crypto/common/Algorithm.i"
	@echo "... src/crypto/common/Algorithm.s"
	@echo "... src/xmrig-cuda.o"
	@echo "... src/xmrig-cuda.i"
	@echo "... src/xmrig-cuda.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

